### ISSUE TITLE
VATSIM Sign-In button doesn't work

### ISSUE THREAD

**Issue by XDerpingxGruntX** [braukStauter/ZAB-Training-Dashboard#1]
**Describe the bug**
No workey

**To Reproduce**
Go to training.zabartcc.net
Clicky Sign-In button
Nothing happen :(

**Expected behavior**
To get the VATSIM SSO page

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Firefox
 - Version: 128.0.3

**Additional context**
Big sad

**Comment by braukStauter** [comment]
Firefox issue, my guess is security due to capturing keystrokes. This is a beta issue that will have no effect on release - closed.
