### ISSUE TITLE
[TODO] Create “View Sent Messages” Logic

### ISSUE THREAD

**Issue by XDerpingxGruntX** [braukStauter/ZAB-Training-Dashboard#2]
**Describe the bug**
When sending messages to other people using the built in message system, the sent message will return to your own inbox, stating "You have a message from John Morgan"

**To Reproduce**
Send someone a message

**Expected behavior**
Inbox should be empty as i have received no messages

**Screenshots**
![image](https://github.com/user-attachments/assets/dc72b855-6929-4c76-9aa7-abd02b819bb2)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Firefox
 - Version: 128.0.3

**Additional context**
Me still sad

**Comment by braukStauter** [comment]
Not really a bug.. that’s how it’s designed right now as there is no “ view sent” functionality. 

To-do: that^

**Comment by braukStauter** [comment]
Complete, will be pushed with V1.1 update.
