### ISSUE TITLE
[TODO] Modify date limit on training availability "end time."

### ISSUE THREAD

**Issue by XDerpingxGruntX** [braukStauter/ZAB-Training-Dashboard#4]
**Describe the bug**
When creating a training request, you are able to set an end date prior to the start date.

**To Reproduce**
Go to training requests tab
Make a new posting
Set start date to a day after current date
Set end date to current date

**Expected behavior**
Scenduling would not be allowed with impossible dates/times

**Screenshots**
![image](https://github.com/user-attachments/assets/e31b3a7f-1e55-4ce8-bdf9-f5d16ef76fb0)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Firefox
 - Version: 128.0.3

**Additional context**
Big funny

**Comment by braukStauter** [comment]
1. Should not be clickable until after start time is input.
a. Start time should also have a limit of current date/time +14 days.
2. End time should have a limit of start date/time +18 hours (to account for block availability)

**Comment by braukStauter** [comment]
Complete, will be pushed with V1.1 update.
