### ISSUE TITLE
Training Request ID bug

### ISSUE THREAD

**Issue by simplybrayden** [braukStauter/ZAB-Training-Dashboard#8]
**Describe the bug**
The Training Requests allow the users to select the section titles or dividers (=== S1 === etc.) in the Request ID field within the Availability posting on the student side.

**To Reproduce**
1. Go to 'Training Requests'
2. Click on 'New Posting'
3. Select the === S1 === options for Req ID

**Screenshots**
<img width="431" alt="image" src="https://github.com/user-attachments/assets/2fac543f-5247-4536-acfa-d554e7b4086e">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX

**Comment by braukStauter** [comment]
Complete, will be pushed with V1.1a
