### ISSUE TITLE
[TODO] I'm an idiot (the same time bug)

### ISSUE THREAD

**Issue by simplybrayden** [braukStauter/ZAB-Training-Dashboard#9]
**Describe the bug**
Student users are allowed to select a starting time before the end time.

**To Reproduce**
1. Go to 'Training Request'
2. Click on 'New Posting'
3. Select a start date and end date on the same day, then select an end time before the start date.

**Screenshots**
<img width="458" alt="image" src="https://github.com/user-attachments/assets/01fabc44-01d8-4443-86ab-89a4712da36a">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX

**Comment by braukStauter** [comment]
Fixed, will be pushed with 1.3a PUB.
